spring.application.name=acquisition-risk-engine

spring.datasource.url=jdbc:postgresql://localhost:5433/acquisition_risk
spring.datasource.username=acquisition_user
spring.datasource.password=acquisition_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration